server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: nurl.ink:8001
  stats:
   locale:
     amap-key: c5af477317639f74a9d1c406cf0d3eec
   goto-domain:
     white-list:
       enable: false
       names: '拿个offer,知乎,掘金,博客园'
       details:
         - nageoffer.com
         - zhihu.com
         - juejin.cn
         - cnblogs.com



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml